blank_issues_enabled: false
contact_links:
    - name: Get Help
      url: https://github.com/Jisc/octopus/discussions/new?category=help
      about: If you can't get something to work the way you expect, open a question in our discussion forums.
    - name: Feature Request
      url: https://github.com/Jisc/octopus/discussions/new?category=ideas
      about: "Suggest any ideas you have using our discussion forums."
    - name: Bug Report
      url: https://github.com/Jisc/octopus/issues/new?body=
      about: If you've already asked for help with a problem and confirmed something is broken, create a bug report.
